<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
 Schema::table('users',fn(Blueprint $t)=>[$t->string('role')->default('monitoring_personnel')->index(),$t->string('status')->default('active')->index()]);
 Schema::create('user_profiles',fn(Blueprint $t)=>[$t->id(),$t->foreignId('user_id')->unique()->constrained()->cascadeOnDelete(),$t->string('contact_no')->nullable(),$t->string('preferred_language')->default('en'),$t->timestamps()]);
 Schema::create('model_versions',fn(Blueprint $t)=>[$t->id(),$t->string('screening_path')->index(),$t->string('architecture'),$t->string('version_name')->unique(),$t->decimal('confidence_threshold',4,2),$t->json('metrics_summary')->nullable(),$t->string('model_size')->nullable(),$t->text('inference_summary')->nullable(),$t->boolean('active')->default(false),$t->timestamps()]);
 Schema::create('disease_classes',fn(Blueprint $t)=>[$t->id(),$t->string('technical_name')->unique(),$t->string('display_name'),$t->string('screening_path')->index(),$t->text('description')->nullable(),$t->boolean('active')->default(true),$t->timestamps()]);
 Schema::create('cases',fn(Blueprint $t)=>[$t->id(),$t->string('case_number')->unique(),$t->foreignId('submitted_by')->constrained('users'),$t->string('screening_path'),$t->string('variety')->nullable(),$t->unsignedSmallInteger('plant_age')->nullable(),$t->string('plant_age_unit')->nullable(),$t->text('symptom_notes')->nullable(),$t->date('observed_at'),$t->string('farm_section')->nullable(),$t->boolean('location_consent')->default(false),$t->string('status')->default('open')->index(),$t->timestamp('referred_at')->nullable(),$t->timestamp('closed_at')->nullable(),$t->timestamps()]);
 Schema::create('case_images',fn(Blueprint $t)=>[$t->id(),$t->foreignId('case_id')->constrained('cases')->cascadeOnDelete(),$t->foreignId('follow_up_id')->nullable(),$t->string('view_type'),$t->string('image_type')->default('original'),$t->string('storage_disk'),$t->string('storage_path'),$t->string('original_filename'),$t->string('mime_type'),$t->unsignedBigInteger('file_size'),$t->unsignedInteger('width'),$t->unsignedInteger('height'),$t->string('image_quality_status'),$t->boolean('metadata_removed')->default(true),$t->timestamp('uploaded_at'),$t->timestamps()]);
 Schema::create('predictions',fn(Blueprint $t)=>[$t->id(),$t->foreignId('case_id')->constrained('cases')->cascadeOnDelete(),$t->foreignId('image_id')->constrained('case_images')->cascadeOnDelete(),$t->foreignId('model_version_id')->nullable()->constrained(),$t->string('predicted_class'),$t->string('display_label'),$t->decimal('confidence',5,4),$t->string('decision_status'),$t->string('quality_status'),$t->json('quality_flags')->nullable(),$t->unsignedInteger('inference_time_ms')->nullable(),$t->text('result_message'),$t->text('disclaimer'),$t->timestamps()]);
 Schema::create('follow_ups',fn(Blueprint $t)=>[$t->id(),$t->foreignId('case_id')->constrained('cases')->cascadeOnDelete(),$t->text('observation')->nullable(),$t->text('action_taken')->nullable(),$t->string('case_status'),$t->foreignId('created_by')->constrained('users'),$t->timestamps()]);
 Schema::create('professional_consultations',fn(Blueprint $t)=>[$t->id(),$t->foreignId('case_id')->constrained('cases')->cascadeOnDelete(),$t->string('reviewer_name'),$t->string('affiliation')->nullable(),$t->string('review_status'),$t->text('professional_notes')->nullable(),$t->boolean('field_inspection_recommended')->default(false),$t->boolean('laboratory_confirmation_recommended')->default(false),$t->timestamp('reviewed_at'),$t->timestamps()]);
 Schema::create('advisories',fn(Blueprint $t)=>[$t->id(),$t->foreignId('disease_id')->constrained('disease_classes'),$t->string('language')->default('en'),$t->text('visible_signs'),$t->text('prevention'),$t->text('containment_reminders'),$t->text('general_guidance'),$t->text('consultation_guidance'),$t->foreignId('reviewed_by')->nullable()->constrained('users'),$t->boolean('active')->default(true),$t->timestamps()]);
 Schema::create('audit_logs',fn(Blueprint $t)=>[$t->id(),$t->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete(),$t->string('action'),$t->string('entity_type'),$t->unsignedBigInteger('entity_id')->nullable(),$t->json('metadata')->nullable(),$t->ipAddress('ip_address')->nullable(),$t->text('user_agent')->nullable(),$t->timestamp('timestamp')->useCurrent()]);
} public function down():void { Schema::dropIfExists('audit_logs');Schema::dropIfExists('advisories');Schema::dropIfExists('professional_consultations');Schema::dropIfExists('follow_ups');Schema::dropIfExists('predictions');Schema::dropIfExists('case_images');Schema::dropIfExists('cases');Schema::dropIfExists('disease_classes');Schema::dropIfExists('model_versions');Schema::dropIfExists('user_profiles');Schema::table('users',fn(Blueprint $t)=>[$t->dropColumn(['role','status'])]); }};
