@extends('layouts.app')
@section('title','Advisory support - BananaShield')
@section('content')
<div class="hero-bar"><div><p class="eyebrow">Advisory Support</p><h1 class="page-title">Managed guidance for supported conditions.</h1><p class="page-copy">Explore visible signs, prevention practices, containment reminders, general management guidance, and consultation cues. Formal content review should be recorded before production use.</p></div></div>
<div class="advisory-tools"><div class="input-wrap"><svg class="input-icon icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><circle cx="11" cy="11" r="7"/><path d="m16 16 5 5"/></svg><input id="advisory-search" class="input" type="search" placeholder="Search advisories and visible signs" aria-label="Search advisories"></div></div>
<div class="advisory-grid" id="advisory-grid">@foreach($advisories as $key=>$item)<article class="card advisory-card {{ $selected===$key ? 'featured' : '' }}" data-search="{{ strtolower($item['title'].' '.$item['summary'].' '.implode(' ',$item['signs'])) }}"><div class="advisory-card-head"><span class="advisory-symbol {{ $item['tone'] }}"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M4 20c8 0 15-5 16-16-8 1-15 8-16 16Z"/></svg></span><div><span class="field-help">{{ $item['path'] }} @if(isset($item['version'])) - {{ $item['version'] }}@endif</span><h2>{{ $item['title'] }}</h2></div></div><p>{{ $item['summary'] }}</p><details {{ $selected===$key ? 'open' : '' }}><summary>View signs and recommendations</summary><div class="advisory-detail"><h3>Visible signs</h3><ul>@foreach($item['signs'] as $line)<li>{{ $line }}</li>@endforeach</ul><h3>Prevention practices</h3><ul>@foreach($item['prevention'] as $line)<li>{{ $line }}</li>@endforeach</ul><h3>Containment reminders</h3><ul>@foreach($item['containment'] as $line)<li>{{ $line }}</li>@endforeach</ul><h3>General management guidance</h3><ul>@foreach($item['guidance'] as $line)<li>{{ $line }}</li>@endforeach</ul><div class="consult-box"><b>When to consult agricultural personnel</b><span>{{ $item['consult'] }}</span></div></div></details></article>@endforeach</div>
<div id="no-advisories" class="card empty-state" hidden><h3>No advisories found</h3><p>Try a broader search.</p></div>
<div class="notice notice-amber" style="margin-top:24px"><span>These are general educational recommendations. BananaShield does not prescribe products or dosages, authorize treatment, or replace professional agricultural assessment or laboratory confirmation.</span></div>
@endsection
@push('scripts')<script>const search=document.getElementById('advisory-search'),cards=[...document.querySelectorAll('.advisory-card')],empty=document.getElementById('no-advisories');search.addEventListener('input',()=>{const q=search.value.trim().toLowerCase();let shown=0;cards.forEach(card=>{const match=card.dataset.search.includes(q);card.hidden=!match;if(match)shown++;});empty.hidden=shown>0;});</script>@endpush
