@extends('layouts.app')
@section('title', 'New guided screening - BananaShield')
@section('content')
<div class="hero-bar"><div><p class="eyebrow">Preliminary Disease Screening</p><h1 class="page-title">Capture or upload a useful plant image.</h1><p class="page-copy">Choose where symptoms are visible, then follow the matching capture guide. Every accepted image is screened by the same four-class EfficientNet-B0 model.</p></div></div>

<div class="stepper" aria-label="Screening progress">
    <div class="step current" data-step="1"><span class="step-num">1</span><span>Main path</span></div><span class="step-line" data-line="1"></span>
    <div class="step" data-step="2"><span class="step-num">2</span><span>Symptom area</span></div><span class="step-line" data-line="2"></span>
    <div class="step" data-step="3"><span class="step-num">3</span><span>Add image</span></div><span class="step-line" data-line="3"></span>
    <div class="step" data-step="4"><span class="step-num">4</span><span>Plant context</span></div><span class="step-line" data-line="4"></span>
    <div class="step" data-step="5"><span class="step-num">5</span><span>Result</span></div>
</div>

<form id="screening-form" method="POST" action="{{ route('screenings.store') }}" enctype="multipart/form-data">@csrf
<div class="screening-layout"><div>
    <section class="card form-section wizard-panel current" data-panel="1">
        <div class="form-section-title"><span class="section-number">01</span><div><h2>Choose the main image path</h2><span class="field-help">Select where the visible symptoms are mainly located.</span></div></div>
        <div class="path-grid">
            <label class="path-option"><input required type="radio" name="image_path" value="leaf" {{ old('image_path', old('screening_path')) === 'leaf' ? 'checked' : '' }}><span class="path-body"><span class="path-selected-indicator" aria-hidden="true"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="m6 12 4 4 8-9"/></svg></span><span class="path-symbol"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M4 20c8 0 15-5 16-16-8 1-15 8-16 16Z"/></svg></span><strong>Leaf</strong><small>Choose this when visible symptoms are mainly found on an individual banana leaf.</small><span class="path-examples">Examples: spots, streaks, lesions, yellowing, discoloration, or abnormal vein patterns.</span></span></label>
            <label class="path-option"><input required type="radio" name="image_path" value="whole_plant" {{ old('image_path', old('screening_path')) === 'whole_plant' ? 'checked' : '' }}><span class="path-body"><span class="path-selected-indicator" aria-hidden="true"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="m6 12 4 4 8-9"/></svg></span><span class="path-symbol"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M12 21V9M12 12C7 12 4 9 4 5c5 0 8 3 8 7ZM12 16c5 0 8-3 8-7-5 0-8 3-8 7Z"/></svg></span><strong>Whole Plant</strong><small>Choose this when symptoms affect the plant's crown, lower leaves, pseudostem, base, or overall appearance.</small><span class="path-examples">Examples: wilting, stunting, bunching, collapsed leaves, yellowing, or pseudostem abnormalities.</span></span></label>
        </div>
        <div class="notice notice-green" style="margin-top:20px"><span>Both paths use the same outputs: Healthy Banana, Black Sigatoka, Fusarium Wilt, and Banana Bunchy Top Disease.</span></div>
        <div class="wizard-actions wizard-actions-end"><button class="btn btn-primary" type="button" data-next="2">Continue</button></div>
    </section>

    <section class="card form-section wizard-panel" data-panel="2" hidden>
        <div class="form-section-title"><span class="section-number">02</span><div><h2>Where are the symptoms most visible?</h2><span class="field-help">Select the specific area that best matches what you want to photograph.</span></div></div>
        <div class="specific-view-group" data-specific-group="leaf" hidden>
            <div class="specific-view-grid specific-view-grid-leaf">
                <label class="specific-view-option"><input type="radio" name="specific_view" value="whole_leaf" data-path-label="Leaf" data-view-label="Whole Leaf" {{ old('specific_view') === 'whole_leaf' ? 'checked' : '' }}><span class="specific-view-body"><span class="specific-view-icon" aria-hidden="true"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M4 20c8 0 15-5 16-16-8 1-15 8-16 16Z"/></svg></span><span class="specific-view-check" aria-hidden="true"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="m6 12 4 4 8-9"/></svg></span><strong>Whole Leaf</strong><small>Choose this when symptoms affect several areas of the leaf or when you are unsure which specific leaf area is affected.</small><span class="specific-capture">Keep most or all of the affected leaf visible in the photograph.</span></span></label>
                <label class="specific-view-option"><input type="radio" name="specific_view" value="leaf_surface" data-path-label="Leaf" data-view-label="Leaf Surface / Blade" {{ old('specific_view') === 'leaf_surface' ? 'checked' : '' }}><span class="specific-view-body"><span class="specific-view-icon" aria-hidden="true"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M4 20c8 0 15-5 16-16-8 1-15 8-16 16Z"/><path d="M7 17c3-4 6-7 10-10"/></svg></span><span class="specific-view-check" aria-hidden="true"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="m6 12 4 4 8-9"/></svg></span><strong>Leaf Surface / Blade</strong><small>Choose this when spots, streaks, lesions, yellowing, discoloration, or necrotic areas are visible on the main leaf surface.</small><span class="specific-capture">Keep the affected leaf surface clearly visible and in focus.</span></span></label>
                <label class="specific-view-option"><input type="radio" name="specific_view" value="leaf_underside" data-path-label="Leaf" data-view-label="Leaf Underside" {{ old('specific_view') === 'leaf_underside' ? 'checked' : '' }}><span class="specific-view-body"><span class="specific-view-icon" aria-hidden="true"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M4 17c7 3 13 1 16-8-7-2-13 1-16 8Z"/><path d="M7 17c3-2 6-4 10-6"/></svg></span><span class="specific-view-check" aria-hidden="true"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="m6 12 4 4 8-9"/></svg></span><strong>Leaf Underside</strong><small>Choose this when symptoms are more visible underneath the banana leaf.</small><span class="specific-capture">Turn the leaf carefully and photograph the underside while keeping visible flecks, streaks, veins, and surrounding leaf tissue in focus.</span></span></label>
                <label class="specific-view-option"><input type="radio" name="specific_view" value="leaf_margins" data-path-label="Leaf" data-view-label="Leaf Margins" {{ old('specific_view') === 'leaf_margins' ? 'checked' : '' }}><span class="specific-view-body"><span class="specific-view-icon" aria-hidden="true"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M4 20c8 0 15-5 16-16-8 1-15 8-16 16Z"/><path d="M6 18c2-1 3-1 4-3s2-2 4-3 2-2 3-4"/></svg></span><span class="specific-view-check" aria-hidden="true"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="m6 12 4 4 8-9"/></svg></span><strong>Leaf Margins</strong><small>Choose this when symptoms are concentrated around the edges of the leaf.</small><span class="specific-examples">Examples: yellowing, browning, drying, or necrotic edges.</span><span class="specific-capture">Include the affected leaf edge together with enough surrounding leaf tissue for context.</span></span></label>
                <label class="specific-view-option"><input type="radio" name="specific_view" value="midrib_veins" data-path-label="Leaf" data-view-label="Midrib &amp; Veins" {{ old('specific_view') === 'midrib_veins' ? 'checked' : '' }}><span class="specific-view-body"><span class="specific-view-icon" aria-hidden="true"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M4 20c8 0 15-5 16-16-8 1-15 8-16 16Z"/><path d="M6 18 18 6M10 14l-1-4M13 11l4 1"/></svg></span><span class="specific-view-check" aria-hidden="true"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="m6 12 4 4 8-9"/></svg></span><strong>Midrib &amp; Veins</strong><small>Choose this when visible symptoms are concentrated along the central midrib or leaf veins.</small><span class="specific-capture">Keep the central midrib, surrounding veins, and affected leaf tissue clearly visible.</span></span></label>
            </div>
        </div>
        <div class="specific-view-group" data-specific-group="whole_plant" hidden>
            <div class="specific-view-grid specific-view-grid-plant">
                <label class="specific-view-option"><input type="radio" name="specific_view" value="full_plant" data-path-label="Whole Plant" data-view-label="Full Plant View" {{ old('specific_view') === 'full_plant' ? 'checked' : '' }}><span class="specific-view-body"><span class="specific-view-icon" aria-hidden="true"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M12 21V8M12 12C7 12 4 9 4 5c5 0 8 3 8 7ZM12 16c5 0 8-3 8-7-5 0-8 3-8 7Z"/></svg></span><span class="specific-view-check" aria-hidden="true"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="m6 12 4 4 8-9"/></svg></span><strong>Full Plant View</strong><small>Choose this when symptoms affect the overall appearance or several parts of the banana plant.</small><span class="specific-examples">Examples: wilting, general yellowing, stunting, abnormal growth, collapsed leaves, or reduced plant vigor.</span><span class="specific-capture">Capture the banana plant from the base to the crown whenever possible.</span></span></label>
                <label class="specific-view-option"><input type="radio" name="specific_view" value="crown_upper_leaves" data-path-label="Whole Plant" data-view-label="Crown &amp; Upper Leaves" {{ old('specific_view') === 'crown_upper_leaves' ? 'checked' : '' }}><span class="specific-view-body"><span class="specific-view-icon" aria-hidden="true"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M12 21V11M12 13C7 13 4 10 4 6c5 0 8 3 8 7ZM12 13c5 0 8-3 8-7-5 0-8 3-8 7ZM12 11V4"/></svg></span><span class="specific-view-check" aria-hidden="true"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="m6 12 4 4 8-9"/></svg></span><strong>Crown &amp; Upper Leaves</strong><small>Choose this when symptoms are most visible around the crown or newly emerging upper leaves.</small><span class="specific-examples">Examples: bunched, upright, narrow, shortened, or distorted leaves and abnormal crown arrangement.</span><span class="specific-capture">Keep the crown, young leaves, and their arrangement clearly visible.</span></span></label>
                <label class="specific-view-option"><input type="radio" name="specific_view" value="lower_older_leaves" data-path-label="Whole Plant" data-view-label="Lower &amp; Older Leaves" {{ old('specific_view') === 'lower_older_leaves' ? 'checked' : '' }}><span class="specific-view-body"><span class="specific-view-icon" aria-hidden="true"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M12 21V7M12 17c-5 0-8-3-8-7 5 0 8 3 8 7ZM12 17c5 0 8-3 8-7-5 0-8 3-8 7Z"/></svg></span><span class="specific-view-check" aria-hidden="true"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="m6 12 4 4 8-9"/></svg></span><strong>Lower &amp; Older Leaves</strong><small>Choose this when symptoms are more noticeable on the lower or older leaves of the plant.</small><span class="specific-examples">Examples: yellowing, drooping, drying, collapsed leaves, dead-leaf skirt, or extensive leaf damage.</span><span class="specific-capture">Capture the lower canopy while keeping affected leaves clearly visible.</span></span></label>
                <label class="specific-view-option"><input type="radio" name="specific_view" value="pseudostem_base" data-path-label="Whole Plant" data-view-label="Pseudostem &amp; Base" {{ old('specific_view') === 'pseudostem_base' ? 'checked' : '' }}><span class="specific-view-body"><span class="specific-view-icon" aria-hidden="true"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M9 21h6l-1-16h-4L9 21Z"/><path d="M6 21h12M10 9h4M9.5 14h5"/></svg></span><span class="specific-view-check" aria-hidden="true"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="m6 12 4 4 8-9"/></svg></span><strong>Pseudostem &amp; Base</strong><small>Choose this when visible symptoms are concentrated on the pseudostem or near the base of the banana plant.</small><span class="specific-examples">Examples: external splitting, abnormal discoloration, or structural abnormalities near the base.</span><span class="specific-capture">Capture the lower pseudostem and plant base clearly without excessive background obstruction.</span></span></label>
            </div>
            <div class="notice notice-amber specific-view-note"><span>Photograph externally visible symptoms only. Do not cut or damage the banana plant.</span></div>
        </div>
        <p class="specific-view-error" id="specific-view-error" role="alert" hidden>Please select where the symptoms are most visible before continuing.</p>
        <div class="wizard-actions"><button class="btn btn-secondary" type="button" data-back="1">Back</button><button class="btn btn-primary" type="button" data-next="3">Continue to image</button></div>
    </section>

    <section class="card form-section wizard-panel" data-panel="3" hidden>
        <div class="form-section-title"><span class="section-number">03</span><div><h2>Add a clear photograph</h2><span class="field-help">JPEG, PNG, or WEBP · up to 5 MB · at least 224 × 224 pixels</span></div></div>
        <div class="selected-view-summary" aria-live="polite"><span>Selected view</span><strong><span id="selected-path-label">—</span><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" aria-hidden="true"><path d="m9 18 6-6-6-6"/></svg><span id="selected-view-label">—</span></strong></div>
        <div class="field-grid capture-layout">
            <label class="upload-box" id="upload-box"><input required accept="image/jpeg,image/png,image/webp" capture="environment" type="file" name="image" id="image-input"><span id="upload-prompt"><span class="upload-icon"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M4 7h4l2-2h4l2 2h4v12H4z"/><circle cx="12" cy="13" r="3"/></svg></span><b>Take or choose a photo</b><small>Use natural light, a steady camera, and keep the selected symptom area clearly visible.</small></span><img id="image-preview" src="{{ asset('images/banana-field.svg') }}" alt="Selected plant image preview"></label>
            <aside class="capture-guide" id="capture-guide" aria-live="polite" aria-atomic="true">
                <div class="capture-guide-heading"><span class="capture-guide-icon" aria-hidden="true"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M5 4h14v16H5zM8 8h8M8 12h6"/></svg></span><div><h3>Capture Guide</h3><p>Follow the instruction for your selected view.</p></div></div>
                <div class="capture-guide-content" data-capture-guide="whole_leaf" hidden><strong>Whole Leaf</strong><p>Keep most or all of the affected leaf visible, with the symptoms and surrounding leaf tissue in focus.</p></div>
                <div class="capture-guide-content" data-capture-guide="leaf_surface" hidden><strong>Leaf Surface / Blade</strong><p>Photograph the main leaf surface. Keep the affected spots, streaks, lesions, or discolored areas clearly visible and in focus.</p></div>
                <div class="capture-guide-content" data-capture-guide="leaf_underside" hidden><strong>Leaf Underside</strong><p>Turn the affected leaf over and photograph the underside. Keep the visible symptoms, veins, and surrounding leaf tissue clearly in focus.</p></div>
                <div class="capture-guide-content" data-capture-guide="leaf_margins" hidden><strong>Leaf Margins</strong><p>Photograph the affected leaf edge together with enough surrounding leaf tissue to show where the symptoms are concentrated.</p></div>
                <div class="capture-guide-content" data-capture-guide="midrib_veins" hidden><strong>Midrib &amp; Veins</strong><p>Keep the central midrib, nearby veins, and affected leaf tissue clearly visible and in focus.</p></div>
                <div class="capture-guide-content" data-capture-guide="full_plant" hidden><strong>Full Plant View</strong><p>Capture the banana plant from the base to the crown whenever possible, keeping its overall shape and affected parts visible.</p></div>
                <div class="capture-guide-content" data-capture-guide="crown_upper_leaves" hidden><strong>Crown &amp; Upper Leaves</strong><p>Capture the top portion of the banana plant. Keep the crown, emerging leaves, and their arrangement clearly visible.</p></div>
                <div class="capture-guide-content" data-capture-guide="lower_older_leaves" hidden><strong>Lower &amp; Older Leaves</strong><p>Capture the lower canopy and keep the affected older leaves clearly visible without obstruction.</p></div>
                <div class="capture-guide-content" data-capture-guide="pseudostem_base" hidden><strong>Pseudostem &amp; Base</strong><p>Capture the lower pseudostem and plant base clearly. Photograph external symptoms only and do not cut or damage the plant.</p></div>
                <ul class="capture-indicators"><li><span aria-hidden="true"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="m6 12 4 4 8-9"/></svg></span>Use sufficient natural light</li><li><span aria-hidden="true"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="m6 12 4 4 8-9"/></svg></span>Keep symptoms in focus</li><li><span aria-hidden="true"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="m6 12 4 4 8-9"/></svg></span>Avoid blur and obstruction</li></ul>
            </aside>
        </div>
        <div class="wizard-actions"><button class="btn btn-secondary" type="button" data-back="2">Back</button><button class="btn btn-primary" type="button" data-next="4">Continue to context</button></div>
    </section>

    <section class="card form-section wizard-panel" data-panel="4" hidden>
        <div class="form-section-title"><span class="section-number">04</span><div><h2>Add available plant context</h2><span class="field-help">Stored with the farm case; not used as model input</span></div></div>
        <div class="field-grid">
            <label class="field"><span class="field-label">Banana variety</span><select name="variety" class="input"><option value="">Not provided</option>@foreach(['Cardava','Binangay','Tundan','Other','Unknown'] as $variety)<option value="{{ $variety }}" @selected(old('variety')===$variety)>{{ $variety }}</option>@endforeach</select></label>
            <label class="field"><span class="field-label">Observation date</span><input required type="date" name="observed_at" value="{{ old('observed_at', date('Y-m-d')) }}" class="input"></label>
            <label class="field"><span class="field-label">Approximate plant age</span><input type="number" min="1" max="3650" name="plant_age" value="{{ old('plant_age') }}" class="input" placeholder="Example: 8"></label>
            <label class="field"><span class="field-label">Age unit</span><select name="plant_age_unit" class="input"><option value="">Not provided</option>@foreach(['weeks','months','years'] as $unit)<option value="{{ $unit }}" @selected(old('plant_age_unit')===$unit)>{{ ucfirst($unit) }}</option>@endforeach</select></label>
            <label class="field"><span class="field-label">Farm section</span><input name="farm_section" value="{{ old('farm_section') }}" maxlength="120" class="input" list="farm-section-options" placeholder="Example: North Block A"><datalist id="farm-section-options">@foreach($farmSections as $section)<option value="{{ $section }}">@endforeach</datalist><span class="field-help" style="display:block;margin-top:8px">Choose a configured farm section or enter another operational label.</span></label>
            <label class="field"><span class="field-label">Banana tree codename</span><input name="tree_codename" value="{{ old('tree_codename') }}" maxlength="120" class="input" placeholder="Example: BA-T014" autocomplete="off"><span class="field-help" style="display:block;margin-top:8px">Add the tag or unique field name used to identify this specific banana tree.</span></label>
        </div>
        <label class="field" style="margin-top:18px"><span class="field-label">Visible symptoms</span><textarea name="symptom_notes" maxlength="2000" class="input" placeholder="Describe spots, yellowing, wilting, drying, stunted growth, or abnormal leaf arrangement.">{{ old('symptom_notes') }}</textarea></label>
        <div class="notice notice-amber" style="margin-top:20px"><span>BananaShield provides preliminary decision support only. Confidence is not confirmation, disease severity, or proof that the predicted class is correct.</span></div>
        <div class="wizard-actions"><button class="btn btn-secondary" type="button" data-back="3">Back</button><button class="btn btn-primary" type="submit">Screen and save farm case</button></div>
    </section>
</div>

<aside class="card sticky-help"><div class="help-top"><span class="feature-icon"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M9 18h6M10 22h4M8 14c-1-1-2-3-2-5a6 6 0 1 1 12 0c0 2-1 4-2 5l-1 2H9z"/></svg></span><h3>Image validation checklist</h3><p>A photograph that does not match the selected symptom area or has poor image quality can produce an inconclusive result.</p></div><ul class="check-list"><li>Use sufficient natural light</li><li>Keep the selected plant area centered</li><li>Avoid blur, obstruction, and digital zoom</li><li>Follow the specific capture guide</li></ul></aside>
</div></form>

<div class="processing-overlay" id="processing-overlay" aria-hidden="true" role="status" aria-live="polite"><div class="processing-card"><div class="processing-mark"><svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M4 20c8 0 15-5 16-16-8 1-15 8-16 16Z"/></svg><span class="processing-ring"></span></div><p class="eyebrow">Preliminary visual screening</p><h2>Processing the plant image</h2><p class="processing-copy">BananaShield is validating and preparing the image, applying the single configured model, and retrieving the corresponding advisory.</p><div class="processing-progress"><span></span></div><ol class="processing-steps"><li class="active">Checking image quality and selected symptom area</li><li>Preparing the accepted image</li><li>Generating a four-class output and confidence score</li><li>Retrieving advisory and saving the farm case</li></ol><p class="processing-note">Keep this page open. Failed requests do not create a completed prediction record.</p></div></div>
@endsection

@push('scripts')<script>
const input=document.getElementById('image-input'),preview=document.getElementById('image-preview'),prompt=document.getElementById('upload-prompt'),form=document.getElementById('screening-form'),overlay=document.getElementById('processing-overlay');
const panels=[...document.querySelectorAll('[data-panel]')],steps=[...document.querySelectorAll('[data-step]')],lines=[...document.querySelectorAll('[data-line]')];
const pathRadios=[...document.querySelectorAll('[name="image_path"]')],specificRadios=[...document.querySelectorAll('[name="specific_view"]')],specificGroups=[...document.querySelectorAll('[data-specific-group]')],captureGuides=[...document.querySelectorAll('[data-capture-guide]')],specificError=document.getElementById('specific-view-error');
function syncCaptureGuide(){const selected=document.querySelector('[name="specific_view"]:checked:not(:disabled)');document.getElementById('selected-path-label').textContent=selected?.dataset.pathLabel||'—';document.getElementById('selected-view-label').textContent=selected?.dataset.viewLabel||'—';captureGuides.forEach(guide=>{guide.hidden=guide.dataset.captureGuide!==selected?.value;});}
function syncSpecificViews(resetSelection=false){const path=document.querySelector('[name="image_path"]:checked')?.value;specificGroups.forEach(group=>{const active=group.dataset.specificGroup===path;group.hidden=!active;group.querySelectorAll('[name="specific_view"]').forEach(radio=>{radio.disabled=!active;if(!active||resetSelection)radio.checked=false;radio.required=false;});});const firstActive=document.querySelector('[name="specific_view"]:not(:disabled)');if(firstActive)firstActive.required=true;specificError.hidden=true;syncCaptureGuide();}
pathRadios.forEach(radio=>radio.addEventListener('change',()=>syncSpecificViews(true)));specificRadios.forEach(radio=>radio.addEventListener('change',()=>{specificError.hidden=true;syncCaptureGuide();}));syncSpecificViews(false);
function validateStep(number){if(number===2&&!document.querySelector('[name="specific_view"]:checked:not(:disabled)')){specificError.hidden=false;document.querySelector('[name="specific_view"]:not(:disabled)')?.focus();return false;}for(const field of document.querySelector(`[data-panel="${number}"]`).querySelectorAll('input,select,textarea')){if(!field.checkValidity()){field.reportValidity();return false;}}return true;}
function showStep(number){panels.forEach(panel=>{const active=Number(panel.dataset.panel)===number;panel.hidden=!active;panel.classList.toggle('current',active);});steps.forEach(step=>{const value=Number(step.dataset.step);step.classList.toggle('current',value===number);step.classList.toggle('completed',value<number);});lines.forEach(line=>line.classList.toggle('completed',Number(line.dataset.line)<number));window.scrollTo({top:document.querySelector('.stepper').offsetTop-95,behavior:'smooth'});}
document.querySelectorAll('[data-next]').forEach(button=>button.addEventListener('click',()=>{const current=Number(button.closest('[data-panel]').dataset.panel);if(validateStep(current))showStep(Number(button.dataset.next));}));document.querySelectorAll('[data-back]').forEach(button=>button.addEventListener('click',()=>showStep(Number(button.dataset.back))));
input?.addEventListener('change',()=>{const file=input.files?.[0];if(!file)return;preview.src=URL.createObjectURL(file);preview.style.display='block';prompt.style.display='none';});
form?.addEventListener('submit',()=>{if(!form.checkValidity())return;overlay.classList.add('visible');overlay.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';});
</script>@endpush
