@extends('layouts.app')
@section('title','System administration - BananaShield')
@section('content')
<div class="hero-bar"><div><p class="eyebrow">Administration and Maintenance</p><h1 class="page-title">Manage operational configuration.</h1><p class="page-copy">Control authorized users, supported categories, versioned advisory content, the single active model registry entry, confidence threshold, and activity records.</p></div></div>
<div class="analytics-warning"><strong>Historical integrity.</strong> Deactivating content or activating a new model does not rewrite predictions already stored with farm cases.</div>

<section class="admin-section"><div class="section-head"><h2>Authorized users</h2><span class="field-help">Three documented roles</span></div><div class="admin-split"><div class="card data-table-wrap"><table class="data-table"><thead><tr><th>User</th><th>Role and status</th><th>Update</th></tr></thead><tbody>@foreach($users as $user)<tr><td><strong>{{ $user->name }}</strong><small>{{ $user->email }}</small></td><td>{{ ucwords(str_replace('_',' ',$user->role)) }}<br>{{ ucfirst($user->status) }}</td><td><form class="inline-admin-form" method="POST" action="{{ route('admin.users.update',$user) }}">@csrf @method('PATCH')<select name="role" class="input input-compact">@foreach(['farm_owner','monitoring_personnel','system_administrator'] as $role)<option value="{{ $role }}" @selected($user->role===$role)>{{ ucwords(str_replace('_',' ',$role)) }}</option>@endforeach</select><select name="status" class="input input-compact"><option value="active" @selected($user->status==='active')>Active</option><option value="inactive" @selected($user->status==='inactive')>Inactive</option></select><button class="btn btn-secondary" type="submit">Save</button></form></td></tr>@endforeach</tbody></table></div><form class="card card-pad form-stack" method="POST" action="{{ route('admin.users.store') }}">@csrf<h3>Create authorized account</h3><label class="field"><span class="field-label">Name</span><input required name="name" class="input"></label><label class="field"><span class="field-label">Email</span><input required type="email" name="email" class="input"></label><label class="field"><span class="field-label">Role</span><select required name="role" class="input"><option value="farm_owner">Farm Owner</option><option value="monitoring_personnel">Monitoring Personnel</option><option value="system_administrator">System Administrator</option></select></label><label class="field"><span class="field-label">Temporary password</span><input required type="password" name="password" class="input" minlength="8"></label><button class="btn btn-primary" type="submit">Create account</button></form></div></section>

<section class="admin-section"><div class="section-head"><h2>Supported disease categories</h2><span class="field-help">Available to both capture paths</span></div><div class="card data-table-wrap"><table class="data-table"><thead><tr><th>Category</th><th>Description</th><th>Active advisory</th><th>Availability</th></tr></thead><tbody>@foreach($diseases as $disease)<tr><td><strong>{{ $disease->display_name }}</strong><small>{{ $disease->technical_name }}</small></td><td>{{ $disease->description }}</td><td>{{ $disease->activeAdvisory?->version_label ?? 'None' }}</td><td><form class="inline-admin-form" method="POST" action="{{ route('admin.diseases.update',$disease) }}">@csrf @method('PATCH')<input type="hidden" name="display_name" value="{{ $disease->display_name }}"><select name="active" class="input input-compact"><option value="1" @selected($disease->active)>Active</option><option value="0" @selected(!$disease->active)>Inactive</option></select><button class="btn btn-secondary" type="submit">Save</button></form></td></tr>@endforeach</tbody></table></div>
<details class="card admin-disclosure"><summary>Add a validated supported category</summary><form class="form-stack" method="POST" action="{{ route('admin.diseases.store') }}">@csrf<div class="field-grid"><label class="field"><span class="field-label">Technical name</span><input required name="technical_name" class="input" placeholder="example_category"></label><label class="field"><span class="field-label">Display name</span><input required name="display_name" class="input"></label></div><label class="field"><span class="field-label">Description</span><textarea name="description" class="input"></textarea></label><button class="btn btn-primary" type="submit">Add category</button></form></details></section>

<section class="admin-section"><div class="section-head"><h2>Versioned advisory content</h2><span class="field-help">Creates a new active version and preserves earlier versions</span></div><details class="card admin-disclosure"><summary>Create and activate advisory version</summary><form class="form-stack" method="POST" action="{{ route('admin.advisories.store') }}">@csrf<div class="field-grid"><label class="field"><span class="field-label">Disease category</span><select required name="disease_id" class="input">@foreach($diseases as $disease)<option value="{{ $disease->id }}">{{ $disease->display_name }}</option>@endforeach</select></label><label class="field"><span class="field-label">Version label</span><input required name="version_label" class="input" placeholder="v2"></label></div>@foreach(['visible_signs'=>'Visible signs (one per line)','prevention'=>'Prevention practices (one per line)','containment_reminders'=>'Containment reminders (one per line)','general_guidance'=>'General guidance (one per line)','consultation_guidance'=>'Professional consultation guidance'] as $name=>$label)<label class="field"><span class="field-label">{{ $label }}</span><textarea required name="{{ $name }}" class="input"></textarea></label>@endforeach<button class="btn btn-primary" type="submit">Activate advisory version</button></form></details></section>

<section class="admin-section"><div class="section-head"><h2>Model registry and confidence threshold</h2><span class="field-help">One active model for both screening paths</span></div><div class="admin-split"><div class="card data-table-wrap"><table class="data-table"><thead><tr><th>Version</th><th>Architecture</th><th>Threshold</th><th>Status</th></tr></thead><tbody>@foreach($models as $model)<tr><td>{{ $model->version_name }}</td><td>{{ $model->architecture }}</td><td>{{ round($model->confidence_threshold*100) }}%</td><td>{{ $model->active ? 'Active' : 'Historical' }}</td></tr>@endforeach</tbody></table></div><form class="card card-pad form-stack" method="POST" action="{{ route('admin.models.store') }}">@csrf<h3>Activate new registry entry</h3><label class="field"><span class="field-label">Architecture</span><input required name="architecture" value="EfficientNet-B0" class="input"></label><label class="field"><span class="field-label">Version name</span><input required name="version_name" class="input"></label><label class="field"><span class="field-label">Validated confidence threshold (0-1)</span><input required type="number" min="0" max="1" step="0.01" name="confidence_threshold" class="input" value="0.75"></label><label class="field"><span class="field-label">Model size</span><input name="model_size" class="input"></label><label class="field"><span class="field-label">Evaluation and inference summary</span><textarea name="inference_summary" class="input"></textarea></label><label class="field"><span class="field-label">Metrics JSON</span><textarea name="metrics_summary" class="input" placeholder='{"test_accuracy": null}'></textarea></label><button class="btn btn-primary" type="submit">Activate model entry</button></form></div></section>

<section class="admin-section"><div class="section-head"><h2>Recent activity logs</h2><span class="field-help">Important administrative and case actions</span></div><div class="card data-table-wrap"><table class="data-table"><thead><tr><th>Time</th><th>User</th><th>Action</th><th>Record</th></tr></thead><tbody>@forelse($logs as $log)<tr><td>{{ $log->timestamp?->format('M j, Y g:i A') }}</td><td>{{ $log->user?->name ?? 'System' }}</td><td>{{ $log->action }}</td><td>{{ class_basename($log->entity_type) }} #{{ $log->entity_id }}</td></tr>@empty<tr><td colspan="4">No activity has been recorded yet.</td></tr>@endforelse</tbody></table></div></section>
@endsection
